#!/usr/bin/env python3
"""Build the pavlab-plotting example gallery (Python + R side-by-side).

Run from skills/plotting/:
    .venv/bin/python examples/build_gallery.py

Outputs:
    examples/gallery/<key>_py.png   (Python figures, all ~3" × 2.8" @ 150 dpi)
    examples/gallery/<key>_r.png    (R figures, generated by build_gallery_R.R)
    examples/gallery/index.html

The R figures require R and ggplot2 / pheatmap. If Rscript is not found the
gallery falls back to Python-only cards.
"""
from __future__ import annotations

import html
import subprocess
import sys
import warnings
from datetime import date
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams.update({"figure.dpi": 150})

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "python"))

from pavlab_density import pavlab_density          # noqa: E402
from pavlab_heatmap import pavlab_heatmap          # noqa: E402
from pavlab_scatter import pavlab_scatter          # noqa: E402
from pavlab_stripchart import pavlab_stripchart    # noqa: E402
from pavlab_boxplot import pavlab_boxplot          # noqa: E402

OUT = Path(__file__).resolve().parent / "gallery"
OUT.mkdir(parents=True, exist_ok=True)

rng = np.random.default_rng(42)
SZ       = (3.0, 2.8)    # standard compact
SZ_STRIP = (3.8, 2.8)    # strip/violin: extra width for group-name x-labels
SZ_HEX   = (3.8, 2.8)    # hexbin: extra width for colorbar
SZ_W     = (5.6, 2.4)    # wide (faceted)
SZ_H     = (3.2, 3.2)    # heatmap


def _q(fn, *a, **kw):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        return fn(*a, **kw)


# ────────────────────────────────────────────────────────────────────────────
#  HEATMAP
# ────────────────────────────────────────────────────────────────────────────

def _expr_mat():
    n_genes, n_samples = 12, 8
    m = pd.DataFrame(
        rng.standard_normal((n_genes, n_samples)),
        index=[f"Gene{i+1:02d}" for i in range(n_genes)],
        columns=[f"S{i+1}" for i in range(n_samples)],
    )
    m.iloc[:4, :4] += 2.5
    m.iloc[:4, 4:] -= 2.5
    return m


def fig_heatmap_expression(out):
    pavlab_heatmap(_expr_mat(), filename=str(out), figsize=SZ_H)

PY_HEATMAP_EXPR = """\
pavlab_heatmap(expr_df)
# rows = genes, cols = samples
# row-standardised → Z-scores, ±3 clip, divergent palette
"""

R_HEATMAP_EXPR = """\
pavlab_heatmap(expr_mat)
"""

PROMPT_HEATMAP_EXPR = (
    "Heatmap of gene expression — row-standardised, Z-clipped, divergent palette."
)


def fig_heatmap_correlation(out):
    cor_mat = _expr_mat().T.corr()
    pavlab_heatmap(cor_mat, mode="correlation", filename=str(out), figsize=SZ_H)

PY_HEATMAP_CORR = """\
pavlab_heatmap(expr_df.T.corr(), mode="correlation")
# diagonal → NA; sequential palette when all correlations ≥ 0
"""

R_HEATMAP_CORR = """\
pavlab_heatmap(cor(t(expr_mat)), mode="correlation")
"""

PROMPT_HEATMAP_CORR = (
    "Sample–sample correlation heatmap; remove diagonal, sequential palette if all positive."
)


def fig_heatmap_raw(out):
    m = pd.DataFrame(
        np.abs(rng.standard_normal((12, 8))) * 5 + 0.5,
        index=[f"Gene{i+1:02d}" for i in range(12)],
        columns=[f"S{i+1}" for i in range(8)],
    )
    pavlab_heatmap(m, mode="raw", filename=str(out), figsize=SZ_H)

PY_HEATMAP_RAW = """\
pavlab_heatmap(raw_df, mode="raw")
# all-positive → black-body sequential palette automatically
"""

R_HEATMAP_RAW = """\
pavlab_heatmap(raw_mat, mode="raw")
"""

PROMPT_HEATMAP_RAW = (
    "Raw intensity heatmap — no Z-scoring, sequential black-body palette."
)


def fig_heatmap_big(out):
    m = pd.DataFrame(
        rng.standard_normal((90, 45)),
        index=[f"g{i+1}" for i in range(90)],
        columns=[f"c{i+1}" for i in range(45)],
    )
    pavlab_heatmap(m, filename=str(out), figsize=(3.6, 3.2))

PY_HEATMAP_BIG = """\
pavlab_heatmap(big_matrix)
# nrow=90, ncol=45 → labels auto-hidden (threshold: 50 rows / 30 cols)
"""

R_HEATMAP_BIG = """\
pavlab_heatmap(big_matrix)  # 90×45 → labels auto-hidden
"""

PROMPT_HEATMAP_BIG = (
    "Large matrix heatmap — too many rows/columns to label; auto-hide."
)


# ────────────────────────────────────────────────────────────────────────────
#  SCATTER
# ────────────────────────────────────────────────────────────────────────────

def fig_scatter_basic(out):
    x = rng.uniform(0.5, 8.0, 80)
    y = np.clip(x * 0.85 + rng.normal(0, 0.7, 80), 0.1, None)
    pavlab_scatter(x, y, xlabel="X", ylabel="Y",
                   title="Basic scatter", label_size="large",
                   filename=str(out), figsize=SZ)

PY_SCATTER_BASIC = """\
pavlab_scatter(x, y, xlabel="X", ylabel="Y")
# ≤500 pts → solid black circles, origin pinned to 0
"""

R_SCATTER_BASIC = """\
pavlab_scatter(x, y, xlabel="X", ylabel="Y")
"""

PROMPT_SCATTER_BASIC = (
    "Simple scatter: two positive arrays, origin at zero, black circles."
)


def fig_scatter_log2_identity(out):
    tpm1 = rng.lognormal(2.0, 2.0, 250)
    tpm2 = tpm1 * rng.lognormal(0, 0.35, 250)
    ax = _q(pavlab_scatter, tpm1, tpm2,
            xlabel="TPM rep 1", ylabel="TPM rep 2",
            log_x="log2", log_y="log2", label_size="large",
            title="Replicate comparison (log₂)")
    ax.axline((0, 0), slope=1, linestyle="--", color="#9ca3af", linewidth=0.8)
    ax.figure.savefig(str(out), bbox_inches="tight")
    plt.close("all")

PY_SCATTER_LOG2 = """\
ax = pavlab_scatter(tpm1, tpm2, log_x="log2", log_y="log2",
                    xlabel="TPM rep 1", ylabel="TPM rep 2")
ax.axline((0, 0), slope=1, linestyle="--", color="#9ca3af")
"""

R_SCATTER_LOG2 = """\
p <- pavlab_scatter(tpm1, tpm2, log_x="log2", log_y="log2")
p + ggplot2::geom_abline(slope=1, linetype="dashed", color="#9ca3af")
"""

PROMPT_SCATTER_LOG2 = (
    "RNA-seq replicates on log₂ scale with an identity line extension."
)


def fig_scatter_categorical(out):
    n = 150
    pc1 = np.concatenate([rng.normal(-2, 1.0, 50),
                           rng.normal(1, 0.8, 50),
                           rng.normal(0, 1.2, 50)])
    pc2 = np.concatenate([rng.normal(1, 0.9, 50),
                           rng.normal(-1, 0.7, 50),
                           rng.normal(2, 1.0, 50)])
    labels = np.array(["Neuron"] * 50 + ["Astrocyte"] * 50 + ["Microglia"] * 50)
    _q(pavlab_scatter, pc1, pc2, color=labels,
       xlabel="PC1 (34%)", ylabel="PC2 (18%)",
       label_size="large",
       origin_zero=False, filename=str(out), figsize=(3.8, 2.8))

PY_SCATTER_CAT = """\
pavlab_scatter(pc1, pc2, color=cell_type_labels,
               xlabel="PC1 (34%)", ylabel="PC2 (18%)",
               origin_zero=False)
"""

R_SCATTER_CAT = """\
pavlab_scatter(pc1, pc2, color=cell_types,
               xlabel="PC1 (34%)", ylabel="PC2 (18%)",
               origin_zero=FALSE)
"""

PROMPT_SCATTER_CAT = (
    "PCA scatter coloured by cell type using the lab accent palette."
)


def fig_scatter_numeric(out):
    x = rng.standard_normal(200)
    y = x * 0.6 + rng.standard_normal(200) * 0.8
    scores = (x + 3) / 6  # 0..1
    pavlab_scatter(x, y, color=scores, color_label="score",
                   origin_zero=False, xlabel="X", ylabel="Y",
                   label_size="large", filename=str(out), figsize=SZ)

PY_SCATTER_NUM = """\
pavlab_scatter(x, y, color=continuous_scores,
               color_label="score", origin_zero=False)
# float array → viridis colormap + colorbar
"""

R_SCATTER_NUM = """\
pavlab_scatter(x, y, color=scores, color_label="score",
               origin_zero=FALSE)
"""

PROMPT_SCATTER_NUM = (
    "Scatter with a continuous colour (viridis colormap + colorbar)."
)


def fig_scatter_hexbin(out):
    n = 25_000
    x = rng.standard_normal(n)
    y = x * 0.65 + rng.standard_normal(n) * 0.76
    _q(pavlab_scatter, x, y, origin_zero=False,
       xlabel="X", ylabel="Y",
       title=f"N = {n:,} — hexbin",
       label_size="large", filename=str(out), figsize=SZ_HEX)

PY_SCATTER_HEX = """\
pavlab_scatter(x, y, origin_zero=False)
# N > 10 000 → hexbin density (black-body palette) automatically
"""

R_SCATTER_HEX = """\
pavlab_scatter(x, y, origin_zero=FALSE)
# N > 10 000 → geom_hex (requires hexbin package)
"""

PROMPT_SCATTER_HEX = (
    "I have expression data for 25,000 cells — individual points would be a black blob. Make it legible."
)


# ────────────────────────────────────────────────────────────────────────────
#  STRIPCHART
# ────────────────────────────────────────────────────────────────────────────

def _strip_data(n_per=50, seed=None):
    r = rng if seed is None else np.random.default_rng(seed)
    groups = np.repeat(["Neuron", "Astrocyte", "Microglia"], n_per)
    vals = np.concatenate([r.lognormal(2.5, 0.8, n_per),
                            r.lognormal(1.9, 0.9, n_per),
                            r.lognormal(2.2, 1.0, n_per)])
    return groups, vals


def fig_strip_basic(out):
    groups, vals = _strip_data()
    _q(pavlab_stripchart, groups, vals,
       xlabel="Cell type", ylabel="TPM",
       log_y="log2", label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_STRIP_BASIC = """\
pavlab_stripchart(cell_type, tpm,
                  xlabel="Cell type", ylabel="TPM",
                  log_y="log2")
# color=None → all black circles
"""

R_STRIP_BASIC = """\
pavlab_stripchart(cell_type, tpm,
                  xlabel="Cell type", ylabel="TPM",
                  log_y="log2")
"""

PROMPT_STRIP_BASIC = (
    "Strip chart of TPM per cell type (log₂ y-axis), all-black circles."
)


def fig_strip_color(out):
    n_per = 30
    groups = np.tile(["Neuron", "Astrocyte", "Microglia"], n_per * 2)
    treat  = np.concatenate([np.tile(["ctrl", "kd"], n_per)] * 3)
    base   = np.concatenate([rng.lognormal(2.5, 0.8, n_per * 2),
                              rng.lognormal(1.9, 0.9, n_per * 2),
                              rng.lognormal(2.2, 1.0, n_per * 2)])
    vals = base * np.where(treat == "kd", 0.55, 1.0)
    _q(pavlab_stripchart, groups, vals, color=treat,
       color_label="Treatment",
       xlabel="Cell type", ylabel="TPM",
       log_y="log2", label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_STRIP_COLOR = """\
pavlab_stripchart(cell_type, tpm,
                  color=treatment, color_label="Treatment",
                  log_y="log2")
# color= stratifies within each group
"""

R_STRIP_COLOR = """\
pavlab_stripchart(cell_type, tpm,
                  color=treatment, color_label="Treatment",
                  log_y="log2")
"""

PROMPT_STRIP_COLOR = (
    "Strip chart stratified by treatment within each cell-type group."
)


def fig_strip_mean_median(out):
    groups = np.repeat(["ctrl", "het", "hom"], 50)
    vals   = np.concatenate([rng.normal(5.1, 0.9, 50),
                              rng.normal(5.8, 1.0, 50),
                              rng.normal(6.5, 1.1, 50)])
    pavlab_stripchart(groups, vals,
                      show_mean=True, show_median=True,
                      xlabel="Genotype", ylabel="Score",
                      order=["ctrl", "het", "hom"],
                      label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_STRIP_MEAN = """\
pavlab_stripchart(genotype, score,
                  show_mean=True, show_median=True,
                  order=["ctrl", "het", "hom"])
# dashed = grand mean  ·  dotted = grand median (gray-400)
"""

R_STRIP_MEAN = """\
pavlab_stripchart(genotype, score,
                  show_mean=TRUE, show_median=TRUE,
                  order=c("ctrl","het","hom"))
"""

PROMPT_STRIP_MEAN = (
    "Strip chart with a dashed grand-mean and dotted grand-median line, explicit group order."
)


def fig_strip_log(out):
    groups, vals = _strip_data(n_per=60)
    _q(pavlab_stripchart, groups, vals,
       log_y="log2", xlabel="Cell type", ylabel="Expression (log₂ TPM+1)",
       origin_zero=False, label_size="large",
       filename=str(out), figsize=SZ_STRIP)

PY_STRIP_LOG = """\
pavlab_stripchart(cell_type, tpm,
                  log_y="log2", origin_zero=False)
# log2 pre-transforms data; axis label gains "(log₂)" suffix
"""

R_STRIP_LOG = """\
pavlab_stripchart(cell_type, tpm,
                  log_y="log2", origin_zero=FALSE)
"""

PROMPT_STRIP_LOG = (
    "Strip chart with log₂ y-axis transform; axis label updated automatically."
)


def fig_strip_swarm(out):
    """Swarm-packed stripchart — non-overlapping point layout."""
    r = np.random.default_rng(13)
    groups = np.repeat(["Neuron", "Astrocyte", "Microglia"], 40)
    vals   = np.concatenate([r.lognormal(2.5, 0.7, 40),
                             r.lognormal(1.9, 0.8, 40),
                             r.lognormal(2.2, 0.9, 40)])
    _q(pavlab_stripchart, groups, vals,
       kind="swarm",
       xlabel="Cell type", ylabel="TPM",
       log_y="log2", label_size="large",
       filename=str(out), figsize=SZ_STRIP)

PY_STRIP_SWARM = """\
pavlab_stripchart(cell_type, tpm, kind="swarm",
                  xlabel="Cell type", ylabel="TPM",
                  log_y="log2")
# beeswarm packs points non-overlappingly — distribution shape is legible
"""

R_STRIP_SWARM = """\
pavlab_stripchart(cell_type, tpm, kind="swarm",
                  xlabel="Cell type", ylabel="TPM",
                  log_y="log2")
# requires the ggbeeswarm package
"""

PROMPT_STRIP_SWARM = (
    "Swarm chart of TPM per cell type — beeswarm packing reveals "
    "distribution shape without overlap."
)


# ────────────────────────────────────────────────────────────────────────────
#  BOXPLOT  (used sparingly — defaults bake in raw points + error bar)
# ────────────────────────────────────────────────────────────────────────────

def _box_data(seed=99):
    r = np.random.default_rng(seed)
    groups = np.repeat(["WT", "KO", "DKO"], 25)
    vals = np.concatenate([
        r.normal(2.0, 0.55, 25),
        r.normal(2.7, 0.75, 25),
        r.normal(3.3, 0.45, 25),
    ])
    return groups, vals


def fig_box_default(out):
    """Default boxplot: pale box + swarmed raw points. No error bar."""
    groups, vals = _box_data()
    _q(pavlab_boxplot, groups, vals,
       xlabel="Genotype", ylabel="Expression",
       order=["WT", "KO", "DKO"],
       label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_BOX_DEFAULT = """\
pavlab_boxplot(genotype, expression,
               xlabel="Genotype", ylabel="Expression",
               order=["WT", "KO", "DKO"])
# defaults: swarmed points underneath + box; no error bar (redundant
# when points are already visible)
"""

R_BOX_DEFAULT = """\
pavlab_boxplot(genotype, expression,
               xlabel="Genotype", ylabel="Expression",
               order=c("WT","KO","DKO"))
"""

PROMPT_BOX_DEFAULT = (
    "Boxplot of expression by genotype — defaults: raw data as a swarm "
    "underneath; no error bar (the points already encode the distribution)."
)


def fig_box_compact(out):
    """Compact box-only chart: no points, no overlaid error bar — the
    whiskers + IQR + median convey the spread on their own."""
    groups, vals = _box_data()
    _q(pavlab_boxplot, groups, vals,
       show_points=False,
       xlabel="Genotype", ylabel="Expression",
       order=["WT", "KO", "DKO"],
       label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_BOX_COMPACT = """\
pavlab_boxplot(genotype, expression, show_points=False,
               order=["WT","KO","DKO"])
# compact box-only chart — whiskers + IQR carry the spread, no overlay
"""

R_BOX_COMPACT = """\
pavlab_boxplot(genotype, expression, show_points = FALSE,
               order = c("WT","KO","DKO"))
"""

PROMPT_BOX_COMPACT = (
    "Compact box-only chart (no raw points) — the box's whiskers + "
    "IQR + median convey the spread; no separate error bar."
)


# ────────────────────────────────────────────────────────────────────────────
#  DENSITY / HISTOGRAM / VIOLIN
# ────────────────────────────────────────────────────────────────────────────

def _dens_data(n_per=200):
    groups = np.repeat(["ctrl", "het", "hom"], n_per)
    vals   = np.concatenate([rng.lognormal(2.0, 0.8, n_per),
                              rng.lognormal(2.5, 0.85, n_per),
                              rng.lognormal(3.0, 0.9, n_per)])
    return groups, vals


def fig_density_single(out):
    # Non-negative, right-skewed (lognormal) data — the natural case for
    # log-scale x. On a linear axis the visible density is a useless
    # spike at zero; log_x exposes the actual shape.
    _, vals = _dens_data(n_per=300)
    _q(pavlab_density, vals, xlabel="Expression", log_x="log2",
       label_size="large", filename=str(out), figsize=SZ)

PY_DENS_SINGLE = """\
pavlab_density(expression_values, xlabel="Expression", log_x="log2")
# non-negative, right-skewed data → propose log scale by default;
# pavlab_density also warns at runtime when data spans > 100× linearly
"""

R_DENS_SINGLE = """\
pavlab_density(expression_values, xlabel="Expression", log_x="log2")
"""

PROMPT_DENS_SINGLE = (
    "Single-group KDE density plot for non-negative, right-skewed "
    "data — log scale on the x-axis."
)


def fig_density_reflect(out):
    vals = rng.exponential(2.0, 400)
    _q(pavlab_density, vals, reflect_bounds=True,
       xlabel="Expression (AU)", label_size="large", filename=str(out), figsize=SZ)

PY_DENS_REFLECT = """\
pavlab_density(expr, reflect_bounds=True, xlabel="Expression (AU)")
# data >= 0 detected; reflection prevents KDE leakage below 0
"""

R_DENS_REFLECT = """\
pavlab_density(expr, reflect_bounds=TRUE, xlabel="Expression (AU)")
"""

PROMPT_DENS_REFLECT = (
    "KDE for non-negative data with boundary reflection — no leakage below zero."
)


def fig_density_grouped(out):
    groups, vals = _dens_data(n_per=150)
    result = _q(pavlab_density, vals, groups=groups, kind="density",
                order=["ctrl", "het", "hom"],
                xlabel="Expression", label_size="large", figsize=SZ)
    result.figure.savefig(str(out), bbox_inches="tight")
    plt.close("all")

PY_DENS_GROUPED = """\
pavlab_density(expression, groups=condition,
               kind="density", order=["ctrl","het","hom"])
# ≤3 groups → overlay; each group gets an accent colour
"""

R_DENS_GROUPED = """\
pavlab_density(expression, groups=condition,
               kind="density", order=c("ctrl","het","hom"))
"""

PROMPT_DENS_GROUPED = (
    "Overlaid density curves for three conditions (≤3 groups)."
)


def fig_density_faceted(out):
    groups, vals = _dens_data(n_per=150)
    fig = _q(pavlab_density, vals, groups=groups, kind="density",
             facet=True, order=["ctrl", "het", "hom"],
             xlabel="Expression", label_size="large", figsize=SZ_W)
    fig.savefig(str(out), bbox_inches="tight")
    plt.close("all")

PY_DENS_FACETED = """\
fig = pavlab_density(expression, groups=condition,
                     kind="density", facet=True,
                     order=["ctrl","het","hom"])
# facet=True → Figure with one panel per group
"""

R_DENS_FACETED = """\
pavlab_density(expression, groups=condition,
               kind="density", facet=TRUE,
               order=c("ctrl","het","hom"))
"""

PROMPT_DENS_FACETED = "Density curves faceted by condition — one panel per group."


def fig_histogram_basic(out):
    _, vals = _dens_data(n_per=200)
    _q(pavlab_density, vals, kind="histogram", stat="count",
       xlabel="Expression", label_size="large", filename=str(out), figsize=SZ)

PY_HIST_BASIC = """\
pavlab_density(expression, kind="histogram", stat="count",
               xlabel="Expression")
"""

R_HIST_BASIC = """\
pavlab_density(expression, kind="histogram", stat="count",
               xlabel="Expression")
"""

PROMPT_HIST_BASIC = "Single-group histogram with count y-axis."


def fig_histogram_faceted(out):
    groups, vals = _dens_data(n_per=200)
    fig = _q(pavlab_density, vals, groups=groups,
             kind="histogram", facet=True, stat="count",
             log_x="log2", order=["ctrl", "het", "hom"],
             xlabel="Expression", label_size="large", figsize=SZ_W)
    fig.savefig(str(out), bbox_inches="tight")
    plt.close("all")

PY_HIST_FACETED = """\
fig = pavlab_density(expression, groups=condition,
                     kind="histogram", facet=True,
                     stat="count", log_x="log2",
                     order=["ctrl","het","hom"])
"""

R_HIST_FACETED = """\
pavlab_density(expression, groups=condition,
               kind="histogram", facet=TRUE,
               stat="count", log_x="log2",
               order=c("ctrl","het","hom"))
"""

PROMPT_HIST_FACETED = "Histograms faceted by condition — log₂ x-axis, count y-axis."


def fig_violin_basic(out):
    groups, vals = _dens_data(n_per=120)
    _q(pavlab_density, vals, groups=groups, kind="violin",
       xlabel="Condition", ylabel="Expression",
       order=["ctrl", "het", "hom"],
       label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_VIOLIN_BASIC = """\
pavlab_density(expression, groups=condition,
               kind="violin", order=["ctrl","het","hom"])
"""

R_VIOLIN_BASIC = """\
pavlab_density(expression, groups=condition,
               kind="violin", order=c("ctrl","het","hom"))
"""

PROMPT_VIOLIN_BASIC = "Violin plot comparing distributions across conditions."


def fig_violin_mean_median(out):
    groups, vals = _dens_data(n_per=120)
    pavlab_density(vals, groups=groups, kind="violin",
                   show_mean=True, show_median=True,
                   xlabel="Condition", ylabel="Expression",
                   order=["ctrl", "het", "hom"],
                   label_size="large", filename=str(out), figsize=SZ_STRIP)

PY_VIOLIN_MEAN = """\
pavlab_density(expression, groups=condition,
               kind="violin",
               show_mean=True, show_median=True,
               order=["ctrl","het","hom"])
# dashed hline = grand mean  ·  dotted = grand median
"""

R_VIOLIN_MEAN = """\
pavlab_density(expression, groups=condition,
               kind="violin",
               show_mean=TRUE, show_median=TRUE,
               order=c("ctrl","het","hom"))
"""

PROMPT_VIOLIN_MEAN = (
    "Violin plot with dashed grand-mean and dotted grand-median reference lines."
)


# ── Registry ─────────────────────────────────────────────────────────────────

FIGURES = [
    # ---- heatmap ----
    dict(key="heatmap_expression",  title="Heatmap — expression (Z-scored)",
         prompt=PROMPT_HEATMAP_EXPR,
         notes="row-standardises → Z-scores, clips ±3 · black-at-zero divergent palette · NA → grey80",
         fn=fig_heatmap_expression, wide=False),
    dict(key="heatmap_correlation", title="Heatmap — sample correlation",
         prompt=PROMPT_HEATMAP_CORR,
         notes="diagonal → NA · sequential (black-body) when min ≥ −0.1 · divergent if more negative",
         fn=fig_heatmap_correlation, wide=False),
    dict(key="heatmap_raw",         title="Heatmap — raw (sequential palette)",
         prompt=PROMPT_HEATMAP_RAW,
         notes="no transform · all-positive → black-body sequential (not divergent)",
         fn=fig_heatmap_raw, wide=False),
    dict(key="heatmap_big",         title="Heatmap — large matrix (labels hidden)",
         prompt=PROMPT_HEATMAP_BIG,
         notes="nrow=90 > 50 threshold → rownames hidden · ncol=45 > 30 → colnames hidden",
         fn=fig_heatmap_big, wide=False),
    # ---- scatter ----
    dict(key="scatter_basic",       title="Scatter — basic",
         prompt=PROMPT_SCATTER_BASIC,
         notes="N=80 ≤ 500 → solid circles, size 20, alpha 1.0 · origin pinned to 0",
         fn=fig_scatter_basic, wide=False),
    dict(key="scatter_log2",        title="Scatter — log₂ replicates + identity line",
         prompt=PROMPT_SCATTER_LOG2,
         notes="log₂(x+1) pre-transform · axis label gains '(log₂)' suffix · identity line via ax.axline / geom_abline",
         fn=fig_scatter_log2_identity, wide=False),
    dict(key="scatter_categorical", title="Scatter — categorical colour",
         prompt=PROMPT_SCATTER_CAT,
         notes="string array → accent palette cycling · one PathCollection / geom_point per group · legend auto-placed",
         fn=fig_scatter_categorical, wide=False),
    dict(key="scatter_numeric",     title="Scatter — numeric colour (viridis)",
         prompt=PROMPT_SCATTER_NUM,
         notes="float array → viridis colormap · continuous colorbar · origin_zero=False",
         fn=fig_scatter_numeric, wide=False),
    dict(key="scatter_hexbin",      title="Scatter — large N hexbin",
         prompt=PROMPT_SCATTER_HEX,
         notes="N=25,000 > 10,000 threshold → hexbin (gridsize=40) · black-body colormap · color= ignored",
         fn=fig_scatter_hexbin, wide=False),
    # ---- stripchart ----
    dict(key="strip_basic",         title="Strip chart — black",
         prompt=PROMPT_STRIP_BASIC,
         notes="color=None → all black · integer x-positions with uniform jitter ±0.2 · log₂ pre-transform",
         fn=fig_strip_basic, wide=False),
    dict(key="strip_color",         title="Strip chart — colour by treatment",
         prompt=PROMPT_STRIP_COLOR,
         notes="color= stratifies within each group · accent palette · jitter preserves group x-position",
         fn=fig_strip_color, wide=False),
    dict(key="strip_mean_median",   title="Strip chart — mean + median lines",
         prompt=PROMPT_STRIP_MEAN,
         notes="show_mean → full-width dashed gray-400 line · show_median → dotted · grand stats, not per-group",
         fn=fig_strip_mean_median, wide=False),
    dict(key="strip_log",           title="Strip chart — log₂ y-axis",
         prompt=PROMPT_STRIP_LOG,
         notes="log₂ pre-transforms values before plotting · axis label gains '(log₂)' suffix · origin_zero=False",
         fn=fig_strip_log, wide=False),
    dict(key="strip_swarm",         title="Strip chart — swarm packing",
         prompt=PROMPT_STRIP_SWARM,
         notes="kind='swarm' · non-overlapping beeswarm layout · display-pixel-aware (Python) / ggbeeswarm (R)",
         fn=fig_strip_swarm, wide=False),
    # ---- boxplot (sparingly!) ----
    dict(key="box_default",         title="Boxplot — default (swarm + box)",
         prompt=PROMPT_BOX_DEFAULT,
         notes="raw points underneath (swarmed) · NO error bar (redundant when points are visible) · no outlier fliers · no quartile-only mode",
         fn=fig_box_default, wide=False),
    dict(key="box_compact",         title="Boxplot — compact (no points)",
         prompt=PROMPT_BOX_COMPACT,
         notes="show_points=False · no points, no error overlay · the box's whiskers + IQR are the spread visualisation",
         fn=fig_box_compact, wide=False),
    # ---- density / histogram / violin ----
    dict(key="density_single",      title="Density — single group",
         prompt=PROMPT_DENS_SINGLE,
         notes="scipy gaussian_kde, bw=scott · fill alpha=0.5 · accent-blue",
         fn=fig_density_single, wide=False),
    dict(key="density_reflect",     title="Density — boundary reflection",
         prompt=PROMPT_DENS_REFLECT,
         notes="appends 2·lo−x; fits KDE; multiplies by 2; zeroes density outside [0,∞) — no boundary leak",
         fn=fig_density_reflect, wide=False),
    dict(key="density_grouped",     title="Density — grouped overlay",
         prompt=PROMPT_DENS_GROUPED,
         notes="≤3 groups → overlay, alpha=0.4 · warns at >3 groups (suggests facet=True)",
         fn=fig_density_grouped, wide=False),
    dict(key="density_faceted",     title="Density — faceted by condition",
         prompt=PROMPT_DENS_FACETED,
         notes="facet=True → Figure with sharey subplots, one KDE panel per group",
         fn=fig_density_faceted, wide=True),
    dict(key="histogram_basic",     title="Histogram — count axis",
         prompt=PROMPT_HIST_BASIC,
         notes="stat='count' → bar heights = raw counts · shared bin edges · alpha=0.7, white dividers",
         fn=fig_histogram_basic, wide=False),
    dict(key="histogram_faceted",   title="Histogram — faceted, log₂ x",
         prompt=PROMPT_HIST_FACETED,
         notes="log₂ pre-transforms values · shared bin edges across panels · one panel per group",
         fn=fig_histogram_faceted, wide=True),
    dict(key="violin_basic",        title="Violin — basic",
         prompt=PROMPT_VIOLIN_BASIC,
         notes="ax.violinplot / geom_violin per group · filled PolyCollection · accent palette",
         fn=fig_violin_basic, wide=False),
    dict(key="violin_mean_median",  title="Violin — mean + median lines",
         prompt=PROMPT_VIOLIN_MEAN,
         notes="axhline/geom_hline at grand mean (dashed) and grand median (dotted) · gray-400, not per-group",
         fn=fig_violin_mean_median, wide=False),
]


# ── HTML ─────────────────────────────────────────────────────────────────────

_CSS = """\
*, *::before, *::after { box-sizing: border-box; }
body {
  font-family: Helvetica, Arial, sans-serif;
  background: #f9fafb;
  color: #1f2937;
  margin: 0;
  padding: 2rem 2rem 4rem;
  font-size: 14px;
}
header { margin-bottom: 2rem; }
h1 { font-size: 1.3rem; font-weight: 400; margin: 0 0 0.2rem; }
.meta { color: #6b7280; font-size: 0.76rem; }
.meta code { font-size: 0.72rem; background: #e5e7eb; padding: 1px 4px; border-radius: 3px; }
.section-label {
  font-size: 0.7rem; font-weight: 700; letter-spacing: 0.08em;
  text-transform: uppercase; color: #9ca3af;
  margin: 2rem 0 0.75rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.25rem;
}
.grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1.25rem;
}
.card {
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 1.1rem;
}
.card h2 {
  font-size: 0.85rem; font-weight: 600;
  margin: 0 0 0.5rem; color: #111827;
}
.prompt {
  background: #eff6ff;
  border-left: 3px solid #2563eb;
  padding: 0.4rem 0.65rem;
  font-style: italic;
  color: #1d4ed8;
  font-size: 0.76rem;
  margin: 0 0 0.7rem;
  border-radius: 0 4px 4px 0;
  line-height: 1.4;
}
.card.span2 { grid-column: span 2; }
.figures { display: flex; gap: 6px; align-items: flex-start; }
.fig-col { flex: 1; min-width: 0; }
.lang-label {
  display: block; font-size: 0.72rem; font-weight: 700; text-align: center;
  letter-spacing: 0.07em; text-transform: uppercase;
  padding: 3px 0; margin: 0 0 5px; border-radius: 3px;
}
.lang-py { background: #dbeafe; color: #1e40af; }
.lang-r  { background: #d1fae5; color: #065f46; }
.fig-col img { width: 100%; height: auto; display: block; border-radius: 2px; }
.notes {
  margin: 0.6rem 0 0;
  font-size: 0.72rem; color: #6b7280;
  font-family: "SFMono-Regular", Consolas, "Courier New", monospace;
  line-height: 1.5;
}
.missing { color: #9ca3af; font-size: 0.72rem; text-align: center; padding: 1rem; }
"""


def _card(f, r_exists):
    key        = f["key"]
    wide       = f["wide"]
    card_class = "card span2" if wide else "card"

    py_img  = f'<img src="gallery/{key}_py.png" alt="Python" loading="lazy">'
    r_block = (f'<img src="gallery/{key}_r.png" alt="R" loading="lazy">'
               if r_exists else '<p class="missing">R figure unavailable</p>')

    notes = html.escape(f.get("notes", ""))

    return f"""\
  <div class="{card_class}" id="{key}">
    <h2>{html.escape(f["title"])}</h2>
    <p class="prompt">&#8220;{html.escape(f["prompt"])}&#8221;</p>
    <div class="figures">
      <div class="fig-col">
        <p class="lang-label lang-py">Python</p>
        {py_img}
      </div>
      <div class="fig-col">
        <p class="lang-label lang-r">R</p>
        {r_block}
      </div>
    </div>
    <p class="notes">{notes}</p>
  </div>"""


_SECTION_KEYS = {
    "Heatmap":    [k for k in ["heatmap_expression","heatmap_correlation","heatmap_raw","heatmap_big"]],
    "Scatter":    ["scatter_basic","scatter_log2","scatter_categorical","scatter_numeric","scatter_hexbin"],
    "Stripchart": ["strip_basic","strip_color","strip_mean_median","strip_log","strip_swarm"],
    "Boxplot (used sparingly)": ["box_default","box_compact"],
    "Density / Histogram / Violin": [
        "density_single","density_reflect","density_grouped",
        "density_faceted","histogram_basic","histogram_faceted",
        "violin_basic","violin_mean_median",
    ],
}


def build_html(figures, r_keys):
    by_key = {f["key"]: f for f in figures}
    sections = []
    for section_name, keys in _SECTION_KEYS.items():
        cards = "\n".join(_card(by_key[k], k in r_keys) for k in keys if k in by_key)
        sections.append(
            f'  <p class="section-label">{html.escape(section_name)}</p>\n'
            f'  <div class="grid">\n{cards}\n  </div>'
        )

    body = "\n".join(sections)
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>pavlab plotting — gallery</title>
  <style>
{_CSS}
  </style>
</head>
<body>
  <header>
    <h1>pavlab plotting — gallery</h1>
    <p class="meta">
      <code>examples/build_gallery.py</code> &nbsp;·&nbsp;
      {len(figures)} examples &nbsp;·&nbsp; {date.today().isoformat()}
    </p>
  </header>
{body}
</body>
</html>"""


# ── main ─────────────────────────────────────────────────────────────────────

def _run_r_script():
    r_script = Path(__file__).resolve().parent / "build_gallery_R.R"
    if not r_script.exists():
        print("  [R] build_gallery_R.R not found — skipping R figures")
        return False
    print("  [R] running build_gallery_R.R ...", end=" ", flush=True)
    try:
        result = subprocess.run(
            ["Rscript", str(r_script)],
            cwd=str(ROOT),
            capture_output=True, text=True, timeout=300,
        )
        if result.returncode == 0:
            print("ok")
            return True
        else:
            print(f"FAILED (exit {result.returncode})")
            if result.stderr:
                for line in result.stderr.strip().splitlines()[-5:]:
                    print(f"    {line}")
            return False
    except FileNotFoundError:
        print("Rscript not found — skipping R figures")
        return False


def main():
    print(f"Output: {OUT}")

    # Python figures
    for f in FIGURES:
        out_path = OUT / f"{f['key']}_py.png"
        print(f"  [py] {f['key']} ...", end=" ", flush=True)
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", UserWarning)
                f["fn"](out_path)
            print(f"ok ({out_path.stat().st_size // 1024} KB)")
        except Exception as e:
            print(f"FAILED: {e}")
            raise

    # R figures
    _run_r_script()

    # Determine which R figures exist
    r_keys = {f["key"] for f in FIGURES if (OUT / f"{f['key']}_r.png").exists()}
    print(f"  R figures present: {len(r_keys)}/{len(FIGURES)}")

    # HTML lives one level up (examples/gallery-index.html) so paths work
    index = OUT.parent / "gallery-index.html"
    index.write_text(build_html(FIGURES, r_keys), encoding="utf-8")
    print(f"\n  gallery-index.html written ({index.stat().st_size // 1024} KB)")
    print(f"\nGallery ready:  open {index}")


if __name__ == "__main__":
    main()
